#!/bin/sh
#
# Copyright (C) 2013 Assaf Gordon <assafgordon@gmail.com>
#
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without
# modifications, as long as this notice is preserved.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

rm -rf config.cache autom4te.cache aclocal.m4 .version .tarball_version

echo "- gnulib."
git submodule update --init gnulib #pull gnulib to a specific git version.
./gnulib/gnulib-tool --update #update used gnulib modules

mkdir -p config
echo "- aclocal."
aclocal -I m4
echo "- autoconf."
autoconf
echo "- autoheader."
autoheader
echo "- automake."
automake -a

echo
echo
echo "now run ./configure"
echo

